/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setVisible(true);
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_arquivo = new javax.swing.JMenu();
        mni_perguntas = new javax.swing.JMenuItem();
        mni_quizz = new javax.swing.JMenuItem();
        mn_sair = new javax.swing.JMenu();
        mni_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setPreferredSize(new java.awt.Dimension(174, 93));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/quiz-header-title (1).png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(479, 201));

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mn_arquivo.setText("Arquivo");

        mni_perguntas.setText("Perguntas");
        mni_perguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_perguntasActionPerformed(evt);
            }
        });
        mn_arquivo.add(mni_perguntas);

        mni_quizz.setText("Quizz");
        mni_quizz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_quizzActionPerformed(evt);
            }
        });
        mn_arquivo.add(mni_quizz);

        jMenuBar1.add(mn_arquivo);

        mn_sair.setText("Sair");

        mni_sair.setText("Sair");
        mni_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_sairActionPerformed(evt);
            }
        });
        mn_sair.add(mni_sair);

        jMenuBar1.add(mn_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mni_sairActionPerformed

    private void mni_perguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_perguntasActionPerformed
        PerguntaView perg = new PerguntaView();
        pnl_principal.removeAll();
        pnl_principal.add(perg);
        pnl_principal.updateUI();
    }//GEN-LAST:event_mni_perguntasActionPerformed

    private void mni_quizzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_quizzActionPerformed
        
        try {
            Quiz quiz = new Quiz();
            pnl_principal.removeAll();
            pnl_principal.add(quiz);
            pnl_principal.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mni_quizzActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mn_arquivo;
    private javax.swing.JMenu mn_sair;
    private javax.swing.JMenuItem mni_perguntas;
    private javax.swing.JMenuItem mni_quizz;
    private javax.swing.JMenuItem mni_sair;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
