/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PerguntaDAO;
import dao.RespostaDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Pergunta;
import model.Resposta;

/**
 *
 * @author Larissa
 */
public class Quiz extends javax.swing.JInternalFrame {

    PerguntaDAO perguntaDAO;
    RespostaDAO respostaDAO;
    List<Pergunta> listaPergunta;
    List<Resposta> listaResposta;
    int contador = 0;
    
    public Quiz()  throws SQLException {
        perguntaDAO = new PerguntaDAO();
        respostaDAO = new RespostaDAO();
        initComponents();
        this.setVisible(true);
        listaPergunta = perguntaDAO.ListaPergunta();
        lbl_pergunta.setText(listaPergunta.get(contador).getDescricao());
        listaResposta = respostaDAO.ListaResposta(listaPergunta.get(contador).getId());
        rb_1.setText(listaResposta.get(0).getDescricao());
        rb_2.setText(listaResposta.get(1).getDescricao());
        rb_3.setText(listaResposta.get(2).getDescricao());
        rb_4.setText(listaResposta.get(3).getDescricao());
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_grupobotao = new javax.swing.ButtonGroup();
        pnl_quiz = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_pergunta = new javax.swing.JLabel();
        rb_1 = new javax.swing.JRadioButton();
        rb_2 = new javax.swing.JRadioButton();
        rb_3 = new javax.swing.JRadioButton();
        rb_4 = new javax.swing.JRadioButton();
        lbl_resposta = new javax.swing.JLabel();
        btn_corrigir = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pergunta");

        lbl_pergunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_grupobotao.add(rb_1);

        btn_grupobotao.add(rb_2);

        btn_grupobotao.add(rb_3);

        btn_grupobotao.add(rb_4);

        lbl_resposta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_corrigir.setBackground(new java.awt.Color(102, 102, 102));
        btn_corrigir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_corrigir.setForeground(new java.awt.Color(255, 255, 255));
        btn_corrigir.setText("Corrigir");
        btn_corrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_corrigirActionPerformed(evt);
            }
        });

        btn_proximo.setBackground(new java.awt.Color(102, 102, 102));
        btn_proximo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_proximo.setForeground(new java.awt.Color(255, 255, 255));
        btn_proximo.setText("Próxima");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_quizLayout = new javax.swing.GroupLayout(pnl_quiz);
        pnl_quiz.setLayout(pnl_quizLayout);
        pnl_quizLayout.setHorizontalGroup(
            pnl_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_quizLayout.createSequentialGroup()
                .addGroup(pnl_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_quizLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_quizLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(pnl_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_2)
                            .addComponent(rb_1)
                            .addComponent(rb_3)
                            .addComponent(rb_4)))
                    .addGroup(pnl_quizLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(pnl_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_quizLayout.createSequentialGroup()
                                .addComponent(lbl_resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btn_corrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pnl_quizLayout.setVerticalGroup(
            pnl_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_quizLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(lbl_pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(rb_1)
                .addGap(18, 18, 18)
                .addComponent(rb_2)
                .addGap(18, 18, 18)
                .addComponent(rb_3)
                .addGap(18, 18, 18)
                .addComponent(rb_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnl_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_corrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_resposta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_quiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_quiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_corrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_corrigirActionPerformed
        if (rb_1.isSelected()) {
            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(0).getId()) {
                lbl_resposta.setText("Acertou!!");
            } else {
                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }
            
        }
        if (rb_2.isSelected()) {
            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(1).getId()) {
                lbl_resposta.setText("Acertou!!");
            } else {
                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }
            
        }
        if (rb_3.isSelected()) {
            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(2).getId()) {
                lbl_resposta.setText("Acertou!!");
            } else {
                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }
            
        }
        if (rb_4.isSelected()) {
            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(3).getId()) {
                lbl_resposta.setText("Acertou!!");
            } else {
                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }
            
        }
    }//GEN-LAST:event_btn_corrigirActionPerformed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
        lbl_resposta.setText("");
        btn_grupobotao.clearSelection();
        contador = contador + 1;
        if (listaPergunta.size() > contador) {
            try {
            lbl_pergunta.setText(listaPergunta.get(contador).getDescricao());
            listaResposta = respostaDAO.ListaResposta(listaPergunta.get(contador).getId());
            rb_1.setText(listaResposta.get(0).getDescricao());
            rb_2.setText(listaResposta.get(1).getDescricao());
            rb_3.setText(listaResposta.get(2).getDescricao());
            rb_4.setText(listaResposta.get(3).getDescricao());
            } catch (SQLException ex) {
                Logger.getLogger(Quiz.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }
        else {
            JOptionPane.showMessageDialog(null, "Fim das questões!!");
            btn_proximo.setEnabled(false);
        }
    }//GEN-LAST:event_btn_proximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_corrigir;
    private javax.swing.ButtonGroup btn_grupobotao;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_pergunta;
    private javax.swing.JLabel lbl_resposta;
    private javax.swing.JPanel pnl_quiz;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_4;
    // End of variables declaration//GEN-END:variables
}
